/** Stable usage reference for web-agent sandboxes without a native MCP client. */
export function renderSandboxManual(mcpEndpoint: string, referenceClientUrl: string): string {
  return [
    '# BlackHole MCP Manual',
    '',
    'This is an informational connection and usage reference for BlackHole in a web-agent sandbox. It is not the user\'s task and does not define, replace, or change BlackHole operating rules; those come from the `guide` tool.',
    'Read it directly, or save it as `BLACKHOLE.md` in the sandbox root if a persistent local reference is useful.',
    '',
    '## Session scope',
    '',
    '- The current BlackHole `sessionId` is supplied separately from this Manual.',
    '- That `sessionId` selects the connected BlackHole session and workspace.',
    '- If the sessionId changes, keep this Manual and `bh.py`; use the new ID on later BlackHole calls. Re-download is not required.',
    '- Call `guide` with the current sessionId to confirm the current project/workspace context and receive the operating rules for that session.',
    '',
    '## Connection',
    '',
    `- MCP endpoint: \`${mcpEndpoint}\``,
    `- Optional reference client: \`${referenceClientUrl}\``,
    '',
    'The sandbox may not have a native MCP client. Either send MCP Streamable HTTP requests directly, or use/read the optional `bh.py` reference client. Both paths reach the same BlackHole MCP.',
    '',
    '> Keep two IDs distinct: BlackHole `sessionId` is the workspace credential passed inside BlackHole tool arguments. `Mcp-Session-Id` is the protocol-session header returned by MCP `initialize`.',
    '',
    '## First use',
    '',
    '1. Connect to the MCP endpoint.',
    '2. Call the BlackHole `guide` tool first with the current BlackHole `sessionId`.',
    '3. List the currently available MCP tools.',
    '4. For each operation, choose the tool that matches that operation. If a tool\'s arguments are unclear, read its current schema instead of guessing.',
    '',
    'The host sandbox and the workspace connected through BlackHole are different environments. Use BlackHole tools when the operation is meant to affect the connected workspace.',
    '',
    '## Direct MCP requests',
    '',
    'Use HTTP POST with:',
    '',
    '```text',
    'Accept: application/json, text/event-stream',
    'Content-Type: application/json',
    'User-Agent: blackhole-sandbox/1.0',
    '```',
    '',
    'Initialize:',
    '',
    '```json',
    '{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"sandbox-agent","version":"1.0.0"}}}',
    '```',
    '',
    'Capture the response `Mcp-Session-Id` header and negotiated protocol version. Send `notifications/initialized` with that protocol-session header, then keep the header (and the negotiated `MCP-Protocol-Version` when applicable) on later requests.',
    '',
    'Read BlackHole `guide` using the current sessionId:',
    '',
    '```json',
    '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"guide","arguments":{"sessionId":"<CURRENT_BLACKHOLE_SESSION_ID>"}}}',
    '```',
    '',
    'List current tools and schemas:',
    '',
    '```json',
    '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}',
    '```',
    '',
    'Call a selected BlackHole tool with `tools/call` and include the current BlackHole `sessionId` in that tool\'s `arguments` unless its current schema/description says otherwise.',
    '',
    'Responses may be JSON or SSE. Read the JSON-RPC result; BlackHole tool output may appear as text content or `structuredContent`.',
    '',
    '## Tool selection',
    '',
    'Choose by the current operation, not by whichever tool was used most recently.',
    '',
    '- precise file reads/edits → `editor`',
    '- unknown code location → `context_search` when it is currently available and appropriate',
    '- finite commands, tests, builds and Git → `exec`',
    '- explicit background servers/watch tasks → `process` when currently available',
    '- other capabilities → use the current `guide` and tool list',
    '',
    'The live `tools/list` result is authoritative for what is available now. Do not copy every schema into long-lived notes; look up the selected tool when needed.',
    '',
    '## Optional `bh.py` reference client',
    '',
    'The reference client is optional and is not bound to a BlackHole sessionId. Save/read it as `bh.py` once, then supply the current ID when using it:',
    '',
    '```text',
    'python3 bh.py --sessionid <CURRENT_BLACKHOLE_SESSION_ID> call guide',
    'python3 bh.py --sessionid <CURRENT_BLACKHOLE_SESSION_ID> tools',
    'python3 bh.py --sessionid <CURRENT_BLACKHOLE_SESSION_ID> tools editor',
    'python3 bh.py --sessionid <CURRENT_BLACKHOLE_SESSION_ID> call <tool-name> <json-arguments>',
    '```',
    '',
    'It handles MCP initialization and JSON/SSE responses, and avoids retrying an ambiguous `tools/call` automatically.',
    '',
    '## Failure and recovery',
    '',
    '- Do not blindly retry a `tools/call` after a lost or ambiguous response; the operation may already have happened. Verify the outcome first.',
    '- Read-only discovery such as `tools/list` can be retried when transport loss makes the result unknown.',
    '- If the conversation becomes long, context is compacted, or tool choice/arguments become unclear, re-read this Manual and the relevant current `guide`/tool schema instead of relying on memory.',
    '- Treat the endpoint and sessionId as connection data. Do not copy them into project files, task outputs, or unrelated logs.',
    '',
  ].join('\n');
}
